version: "3.5"
services:
  maven:
    build:
      context: .
      dockerfile: dev.dockerfile
    volumes:
      - ./../:/app
      - maven-repo:/root/.m2
    command: clean install
  app:
    build:
      context: .
      dockerfile: dev.dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./../:/app
      - maven-repo:/root/.m2
    command: spring-boot:run

volumes:
  maven-repo: